extends Node
## Localization - lightweight string table with runtime language switching.

signal language_changed(lang: String)

const LANGS := ["en", "es", "de", "fr", "pt", "ja"]

var lang := "en"
var _table: Dictionary = {}


func _ready() -> void:
	lang = str(SettingsManager.get_ui("language"))
	if not LANGS.has(lang):
		lang = "en"
	load_table(lang)


func load_table(code: String) -> void:
	_table = TABLES.get(code, TABLES["en"])
	lang = code
	SettingsManager.set_ui("language", code)
	language_changed.emit(code)


func set_language(code: String) -> void:
	if not LANGS.has(code):
		return
	load_table(code)


func t(key: String) -> String:
	return str(_table.get(key, TABLES["en"].get(key, key)))


func trf(key: String, args: Array) -> String:
	var s := t(key)
	for i in args.size():
		s = s.replace("{%d}" % i, str(args[i]))
	return s


const TABLES := {
	"en": {
		"app.title": "DEX DASH",
		"app.tagline": "a rhythm platformer",
		"menu.play": "Play",
		"menu.story": "Story",
		"menu.endless": "Endless",
		"menu.daily": "Daily",
		"menu.editor": "Editor",
		"menu.custom": "Custom Levels",
		"menu.settings": "Settings",
		"menu.stats": "Statistics",
		"menu.achievements": "Achievements",
		"menu.icons": "Icons",
		"menu.quit": "Quit",
		"menu.continue": "Continue",
		"menu.level_select": "Level Select",
		"menu.main_menu": "Main Menu",
		"menu.modes": "Game Modes",
		"back": "Back",
		"yes": "Yes",
		"no": "No",
		"ok": "OK",
		"cancel": "Cancel",
		"confirm": "Confirm",
		"retry": "Retry",
		"continue": "Continue",
		"play": "Play",
		"practice": "Practice",
		"normal": "Normal",
		"easy": "Easy",
		"hard": "Hard",
		"harder": "Harder",
		"insane": "Insane",
		"extreme": "Extreme",
		"demon": "Demon",
		"tutorial": "Tutorial",
		"level": "Level",
		"coins": "Coins",
		"attempts": "Attempts",
		"jumps": "Jumps",
		"deaths": "Deaths",
		"time": "Time",
		"best": "Best",
		"complete": "Complete",
		"level_complete": "Level Complete!",
		"level_failed": "Level Failed",
		"new_best": "New Best!",
		"coins_collected": "Coins collected",
		"secret_found": "Secret found!",
		"press_enter": "Press Enter",
		"tap_anywhere": "Tap anywhere to start",
		"loading": "Loading",
		"paused": "Paused",
		"resume": "Resume",
		"restart": "Restart",
		"quit_to_menu": "Quit to Menu",
		"checkpoint_reached": "Checkpoint!",
		"practice_mode": "Practice Mode",
		"auto_retry": "Auto retry",
		"tap_to_restart": "Tap to restart",
		"ghost_mode": "Ghost mode",
		"show_fps": "Show FPS",
		"screen_shake": "Screen shake",
		"background_detail": "Background detail",
		"particles": "Particles",
		"quality": "Quality",
		"quality_low": "Low",
		"quality_medium": "Medium",
		"quality_high": "High",
		"vsync": "VSync",
		"fps_limit": "FPS limit",
		"fullscreen": "Fullscreen",
		"resolution": "Resolution",
		"master_volume": "Master volume",
		"music_volume": "Music volume",
		"sfx_volume": "SFX volume",
		"language": "Language",
		"theme": "Color theme",
		"controls": "Controls",
		"rebind_jump": "Jump",
		"rebind_pause": "Pause",
		"reset_controls": "Reset controls",
		"accessibility": "Accessibility",
		"reduced_motion": "Reduced motion",
		"high_contrast": "High contrast",
		"colorblind": "Colorblind mode",
		"ui_scale": "UI scale",
		"statistics": "Statistics",
		"stat.jumps": "Total jumps",
		"stat.deaths": "Total deaths",
		"stat.attempts": "Total attempts",
		"stat.time": "Time played",
		"stat.levels": "Levels completed",
		"stat.coins": "Coins collected",
		"stat.secret_coins": "Secret coins",
		"stat.endless": "Endless best",
		"stat.daily": "Daily best",
		"stat.achievements": "Achievements",
		"achievements": "Achievements",
		"achievements_progress": "Unlocked {0} of {1}",
		"icon_shop": "Icon Shop",
		"icon_color": "Color",
		"icon_trail": "Trail",
		"buy": "Buy",
		"equip": "Equip",
		"owned": "Owned",
		"not_enough_coins": "Not enough coins",
		"custom_levels": "Custom Levels",
		"create_level": "Create Level",
		"play_custom": "Play",
		"edit": "Edit",
		"delete": "Delete",
		"delete_confirm": "Delete this level?",
		"editor": "Level Editor",
		"editor.palette": "Objects",
		"editor.undo": "Undo",
		"editor.redo": "Redo",
		"editor.playtest": "Playtest",
		"editor.save": "Save",
		"editor.export": "Export",
		"editor.import": "Import",
		"editor.grid": "Grid",
		"editor.layers": "Layers",
		"editor.trigger": "Triggers",
		"editor.search": "Search",
		"editor.untitled": "Untitled Level",
		"editor.name": "Level name",
		"editor.music": "Music",
		"editor.theme": "Theme",
		"editor.difficulty": "Difficulty",
		"editor.saved": "Level saved",
		"editor.exported": "Level copied to clipboard",
		"editor.imported": "Level imported",
		"editor.start_pos": "Start position",
		"editor.clear": "Clear",
		"editor.clear_confirm": "Clear the entire level?",
		"daily": "Daily Challenge",
		"daily.desc": "A new level every day. Same for everyone!",
		"daily.done": "Daily completed! Come back tomorrow.",
		"endless": "Endless Mode",
		"endless.desc": "How far can you go?",
		"endless.score": "Distance",
		"story": "Story Mode",
		"story.desc": "Follow DEX on the Neon Circuit",
		"boss": "Boss",
		"boss.warning": "THE WARDEN AWAITS",
		"level_locked": "Complete previous levels to unlock",
		"leaderboard": "Leaderboard",
		"leaderboard.local": "Local bests",
		"leaderboard.global": "Global (coming soon)",
		"best_time": "Best time",
		"practice_best": "Practice best",
		"replay": "Replay",
		"ghost_beaten": "You beat your ghost!",
		"ghost_faster": "Ghost is still ahead",
		"new_record": "New record!",
		"achievement_unlocked": "Achievement unlocked",
		"skip": "Skip",
		"next": "Next",
		"story_text.1": "Welcome to the Neon Circuit.",
		"story_text.2": "I am DEX. This is my dash.",
		"story_text.3": "Every beat carries me forward.",
		"story_text.4": "Portals bend my path. Gravity betrays me.",
		"story_text.5": "The Wardens guard the depths.",
		"story_text.6": "I will outrun them all.",
		"story_text.7": "The Circuit never ends...",
		"story_text.8": "...and neither do I.",
		"fps": "FPS",
		"progress": "Progress",
		"restart_confirm": "Restart the level?",
		"quit_confirm": "Quit to menu?",
		"delete_save": "Delete save data",
		"delete_save_confirm": "This cannot be undone. Delete all progress?",
		"reset": "Reset",
		"version": "Version",
		"controls_hint": "Space / W / Up - jump | Esc - pause | R - restart",
		"how_to_play": "Hold to jump higher. Land to flip. Portals change everything.",
		"multilingual.credit": "Translations are community-contributed.",
	},
	"es": {
		"app.title": "DEX DASH",
		"app.tagline": "un plataformer ritmico",
		"menu.play": "Jugar",
		"menu.story": "Historia",
		"menu.endless": "Infinito",
		"menu.daily": "Diario",
		"menu.editor": "Editor",
		"menu.custom": "Niveles Personalizados",
		"menu.settings": "Ajustes",
		"menu.stats": "Estadisticas",
		"menu.achievements": "Logros",
		"menu.icons": "Iconos",
		"menu.quit": "Salir",
		"menu.continue": "Continuar",
		"menu.level_select": "Seleccion de Nivel",
		"menu.main_menu": "Menu Principal",
		"back": "Volver",
		"yes": "Si",
		"no": "No",
		"ok": "OK",
		"cancel": "Cancelar",
		"confirm": "Confirmar",
		"retry": "Reintentar",
		"continue": "Continuar",
		"play": "Jugar",
		"practice": "Practica",
		"normal": "Normal",
		"easy": "Facil",
		"hard": "Dificil",
		"harder": "Mas Dificil",
		"insane": "Insano",
		"extreme": "Extremo",
		"demon": "Demonio",
		"tutorial": "Tutorial",
		"level": "Nivel",
		"coins": "Monedas",
		"attempts": "Intentos",
		"jumps": "Saltos",
		"deaths": "Muertes",
		"time": "Tiempo",
		"best": "Mejor",
		"complete": "Completado",
		"level_complete": "Nivel Completado!",
		"level_failed": "Nivel Fallido",
		"new_best": "Nuevo Record!",
		"coins_collected": "Monedas recogidas",
		"secret_found": "Secreto encontrado!",
		"press_enter": "Pulsa Enter",
		"tap_anywhere": "Toca en cualquier lugar para empezar",
		"loading": "Cargando",
		"paused": "Pausado",
		"resume": "Reanudar",
		"restart": "Reiniciar",
		"quit_to_menu": "Salir al Menu",
		"checkpoint_reached": "Punto de control!",
		"practice_mode": "Modo Practica",
		"auto_retry": "Reintento automatico",
		"tap_to_restart": "Toca para reiniciar",
		"ghost_mode": "Modo fantasma",
		"show_fps": "Mostrar FPS",
		"screen_shake": "Sacudida de pantalla",
		"background_detail": "Detalle de fondo",
		"particles": "Particulas",
		"quality": "Calidad",
		"quality_low": "Baja",
		"quality_medium": "Media",
		"quality_high": "Alta",
		"vsync": "VSync",
		"fps_limit": "Limite de FPS",
		"fullscreen": "Pantalla completa",
		"resolution": "Resolucion",
		"master_volume": "Volumen general",
		"music_volume": "Volumen musica",
		"sfx_volume": "Volumen efectos",
		"language": "Idioma",
		"theme": "Tema de color",
		"controls": "Controles",
		"rebind_jump": "Saltar",
		"rebind_pause": "Pausa",
		"reset_controls": "Restablecer controles",
		"accessibility": "Accesibilidad",
		"reduced_motion": "Movimiento reducido",
		"high_contrast": "Alto contraste",
		"colorblind": "Modo daltonico",
		"ui_scale": "Escala de interfaz",
		"statistics": "Estadisticas",
		"stat.jumps": "Saltos totales",
		"stat.deaths": "Muertes totales",
		"stat.attempts": "Intentos totales",
		"stat.time": "Tiempo jugado",
		"stat.levels": "Niveles completados",
		"stat.coins": "Monedas recogidas",
		"stat.secret_coins": "Monedas secretas",
		"stat.endless": "Mejor en infinito",
		"stat.daily": "Mejor diario",
		"stat.achievements": "Logros",
		"achievements": "Logros",
		"achievements_progress": "Desbloqueados {0} de {1}",
		"icon_shop": "Tienda de Iconos",
		"icon_color": "Color",
		"icon_trail": "Estela",
		"buy": "Comprar",
		"equip": "Equipar",
		"owned": "Adquirido",
		"not_enough_coins": "Monedas insuficientes",
		"custom_levels": "Niveles Personalizados",
		"create_level": "Crear Nivel",
		"play_custom": "Jugar",
		"edit": "Editar",
		"delete": "Borrar",
		"delete_confirm": "Borrar este nivel?",
		"editor": "Editor de Niveles",
		"editor.palette": "Objetos",
		"editor.undo": "Deshacer",
		"editor.redo": "Rehacer",
		"editor.playtest": "Probar",
		"editor.save": "Guardar",
		"editor.export": "Exportar",
		"editor.import": "Importar",
		"editor.grid": "Cuadricula",
		"editor.layers": "Capas",
		"editor.trigger": "Disparadores",
		"editor.search": "Buscar",
		"editor.untitled": "Nivel sin titulo",
		"editor.name": "Nombre del nivel",
		"editor.music": "Musica",
		"editor.theme": "Tema",
		"editor.difficulty": "Dificultad",
		"editor.saved": "Nivel guardado",
		"editor.exported": "Nivel copiado al portapapeles",
		"editor.imported": "Nivel importado",
		"editor.start_pos": "Posicion inicial",
		"editor.clear": "Limpiar",
		"editor.clear_confirm": "Limpiar todo el nivel?",
		"daily": "Desafio Diario",
		"daily.desc": "Un nivel nuevo cada dia. Igual para todos!",
		"daily.done": "Diario completado! Vuelve manana.",
		"endless": "Modo Infinito",
		"endless.desc": "Hasta donde puedes llegar?",
		"endless.score": "Distancia",
		"story": "Modo Historia",
		"story.desc": "Acompania a DEX en el Circuito Neon",
		"boss": "Jefe",
		"boss.warning": "EL GUARDIAN TE ESPERA",
		"level_locked": "Completa niveles anteriores para desbloquear",
		"leaderboard": "Clasificacion",
		"leaderboard.local": "Mejores locales",
		"leaderboard.global": "Global (proximamente)",
		"best_time": "Mejor tiempo",
		"practice_best": "Mejor en practica",
		"replay": "Repeticion",
		"ghost_beaten": "Has superado a tu fantasma!",
		"ghost_faster": "El fantasma sigue adelante",
		"new_record": "Nuevo record!",
		"achievement_unlocked": "Logro desbloqueado",
		"skip": "Saltar",
		"next": "Siguiente",
		"story_text.1": "Bienvenido al Circuito Neon.",
		"story_text.2": "Soy DEX. Esta es mi carrera.",
		"story_text.3": "Cada ritmo me impulsa.",
		"story_text.4": "Los portales tuercen mi camino. La gravedad me traiciona.",
		"story_text.5": "Los Guardianes custodian las profundidades.",
		"story_text.6": "Les superare a todos.",
		"story_text.7": "El Circuito nunca termina...",
		"story_text.8": "...y yo tampoco.",
		"fps": "FPS",
		"progress": "Progreso",
		"restart_confirm": "Reiniciar el nivel?",
		"quit_confirm": "Salir al menu?",
		"delete_save": "Borrar datos guardados",
		"delete_save_confirm": "Esto no se puede deshacer. Borrar todo el progreso?",
		"reset": "Reiniciar",
		"version": "Version",
		"controls_hint": "Espacio / W / Arriba - saltar | Esc - pausa | R - reiniciar",
		"how_to_play": "Mantener para saltar mas alto. Aterriza para girar. Los portales lo cambian todo.",
		"multilingual.credit": "Las traducciones son aportadas por la comunidad.",
	},
	"de": {
		"app.title": "DEX DASH",
		"app.tagline": "ein Rhythmus-Platformer",
		"menu.play": "Spielen",
		"menu.story": "Story",
		"menu.endless": "Endlos",
		"menu.daily": "TÃ¤glich",
		"menu.editor": "Editor",
		"menu.custom": "Eigene Level",
		"menu.settings": "Einstellungen",
		"menu.stats": "Statistiken",
		"menu.achievements": "Errungenschaften",
		"menu.icons": "Icons",
		"menu.quit": "Beenden",
		"menu.continue": "Weiter",
		"menu.level_select": "Levelauswahl",
		"menu.main_menu": "HauptmenÃ¼",
		"back": "ZurÃ¼ck",
		"yes": "Ja",
		"no": "Nein",
		"ok": "OK",
		"cancel": "Abbrechen",
		"confirm": "BestÃ¤tigen",
		"retry": "Erneut",
		"continue": "Weiter",
		"play": "Spielen",
		"practice": "Ãœbung",
		"normal": "Normal",
		"easy": "Leicht",
		"hard": "Schwer",
		"harder": "Schwerer",
		"insane": "Irrsinnig",
		"extreme": "Extrem",
		"demon": "DÃ¤mon",
		"tutorial": "Tutorial",
		"level": "Level",
		"coins": "MÃ¼nzen",
		"attempts": "Versuche",
		"jumps": "SprÃ¼nge",
		"deaths": "Tode",
		"time": "Zeit",
		"best": "Best",
		"complete": "AbschlieÃŸen",
		"level_complete": "Level Geschafft!",
		"level_failed": "Level Fehlgeschlagen",
		"new_best": "Neuer Rekord!",
		"coins_collected": "MÃ¼nzen gesammelt",
		"secret_found": "Geheimnis gefunden!",
		"press_enter": "Enter drÃ¼cken",
		"tap_anywhere": "Zum Starten tippen",
		"loading": "Laden",
		"paused": "Pausiert",
		"resume": "Weiterspielen",
		"restart": "Neustart",
		"quit_to_menu": "Zum MenÃ¼",
		"checkpoint_reached": "Kontrollpunkt!",
		"practice_mode": "Ãœbungsmodus",
		"auto_retry": "Auto-Wiederholung",
		"tap_to_restart": "Zum Neustart tippen",
		"ghost_mode": "Geistermodus",
		"show_fps": "FPS anzeigen",
		"screen_shake": "Bildschirm wackeln",
		"background_detail": "Hintergrunddetails",
		"particles": "Partikel",
		"quality": "QualitÃ¤t",
		"quality_low": "Niedrig",
		"quality_medium": "Mittel",
		"quality_high": "Hoch",
		"vsync": "VSync",
		"fps_limit": "FPS-Limit",
		"fullscreen": "Vollbild",
		"resolution": "AuflÃ¶sung",
		"master_volume": "HauptlautstÃ¤rke",
		"music_volume": "MusiklautstÃ¤rke",
		"sfx_volume": "EffektlautstÃ¤rke",
		"language": "Sprache",
		"theme": "Farbschema",
		"controls": "Steuerung",
		"rebind_jump": "Springen",
		"rebind_pause": "Pause",
		"reset_controls": "Steuerung zurÃ¼cksetzen",
		"accessibility": "Barrierefreiheit",
		"reduced_motion": "Reduzierte Bewegung",
		"high_contrast": "Hoher Kontrast",
		"colorblind": "Farbenblind-Modus",
		"ui_scale": "UI-Skalierung",
		"statistics": "Statistiken",
		"stat.jumps": "SprÃ¼nge gesamt",
		"stat.deaths": "Tode gesamt",
		"stat.attempts": "Versuche gesamt",
		"stat.time": "Spielzeit",
		"stat.levels": "Level abgeschlossen",
		"stat.coins": "MÃ¼nzen gesammelt",
		"stat.secret_coins": "GeheimmÃ¼nzen",
		"stat.endless": "Endlos-Rekord",
		"stat.daily": "Tages-Rekord",
		"stat.achievements": "Errungenschaften",
		"achievements": "Errungenschaften",
		"achievements_progress": "{0} von {1} freigeschaltet",
		"icon_shop": "Icon-Shop",
		"icon_color": "Farbe",
		"icon_trail": "Spur",
		"buy": "Kaufen",
		"equip": "AusrÃ¼sten",
		"owned": "Besessen",
		"not_enough_coins": "Nicht genug MÃ¼nzen",
		"custom_levels": "Eigene Level",
		"create_level": "Level erstellen",
		"play_custom": "Spielen",
		"edit": "Bearbeiten",
		"delete": "LÃ¶schen",
		"delete_confirm": "Dieses Level lÃ¶schen?",
		"editor": "Level-Editor",
		"editor.palette": "Objekte",
		"editor.undo": "RÃ¼ckgÃ¤ngig",
		"editor.redo": "Wiederholen",
		"editor.playtest": "Testen",
		"editor.save": "Speichern",
		"editor.export": "Exportieren",
		"editor.import": "Importieren",
		"editor.grid": "Raster",
		"editor.layers": "Ebenen",
		"editor.trigger": "Trigger",
		"editor.search": "Suchen",
		"editor.untitled": "Unbenanntes Level",
		"editor.name": "Levelname",
		"editor.music": "Musik",
		"editor.theme": "Thema",
		"editor.difficulty": "Schwierigkeit",
		"editor.saved": "Level gespeichert",
		"editor.exported": "Level in Zwischenablage kopiert",
		"editor.imported": "Level importiert",
		"editor.start_pos": "Startposition",
		"editor.clear": "Leeren",
		"editor.clear_confirm": "Ganzes Level leeren?",
		"daily": "Tages-Challenge",
		"daily.desc": "Jeden Tag ein neues Level. FÃ¼r alle gleich!",
		"daily.done": "Tages-Challenge geschafft! Bis morgen.",
		"endless": "Endlosmodus",
		"endless.desc": "Wie weit kommst du?",
		"endless.score": "Distanz",
		"story": "Story-Modus",
		"story.desc": "Folge DEX auf dem Neon-Circuit",
		"boss": "Boss",
		"boss.warning": "DER WARDEN ERWARTET DICH",
		"level_locked": "SchlieÃŸe vorherige Level ab",
		"leaderboard": "Bestenliste",
		"leaderboard.local": "Lokale Bestzeiten",
		"leaderboard.global": "Global (bald verfÃ¼gbar)",
		"best_time": "Beste Zeit",
		"practice_best": "Ãœbungs-Rekord",
		"replay": "Wiederholung",
		"ghost_beaten": "Du hast deinen Geist geschlagen!",
		"ghost_faster": "Der Geist ist noch vorn",
		"new_record": "Neuer Rekord!",
		"achievement_unlocked": "Errungenschaft freigeschaltet",
		"skip": "Ãœberspringen",
		"next": "Weiter",
		"story_text.1": "Willkommen im Neon-Circuit.",
		"story_text.2": "Ich bin DEX. Das ist mein Dash.",
		"story_text.3": "Jeder Beat trÃ¤gt mich voran.",
		"story_text.4": "Portale verbiegen meinen Weg. Schwerkraft betrÃ¼gt mich.",
		"story_text.5": "Die Wardens bewachen die Tiefen.",
		"story_text.6": "Ich werde sie alle Ã¼berholen.",
		"story_text.7": "Der Circuit endet nie...",
		"story_text.8": "...und ich auch nicht.",
		"fps": "FPS",
		"progress": "Fortschritt",
		"restart_confirm": "Level neu starten?",
		"quit_confirm": "Zum MenÃ¼?",
		"delete_save": "Spielstand lÃ¶schen",
		"delete_save_confirm": "Das kann nicht rÃ¼ckgÃ¤ngig gemacht werden. Alles lÃ¶schen?",
		"reset": "ZurÃ¼cksetzen",
		"version": "Version",
		"controls_hint": "Leertaste / W / Hoch - springen | Esc - Pause | R - Neustart",
		"how_to_play": "Halten fÃ¼r hÃ¶here SprÃ¼nge. Landen zum Drehen. Portale Ã¤ndern alles.",
		"multilingual.credit": "Ãœbersetzungen stammen aus der Community.",
	},
	"fr": {
		"app.title": "DEX DASH",
		"app.tagline": "un platformer rythmique",
		"menu.play": "Jouer",
		"menu.story": "Histoire",
		"menu.endless": "Infini",
		"menu.daily": "Quotidien",
		"menu.editor": "Ã‰diteur",
		"menu.custom": "Niveaux Perso",
		"menu.settings": "RÃ©glages",
		"menu.stats": "Statistiques",
		"menu.achievements": "SuccÃ¨s",
		"menu.icons": "IcÃ´nes",
		"menu.quit": "Quitter",
		"menu.continue": "Continuer",
		"menu.level_select": "SÃ©lection de Niveaux",
		"menu.main_menu": "Menu Principal",
		"back": "Retour",
		"yes": "Oui",
		"no": "Non",
		"ok": "OK",
		"cancel": "Annuler",
		"confirm": "Confirmer",
		"retry": "RÃ©essayer",
		"continue": "Continuer",
		"play": "Jouer",
		"practice": "EntraÃ®nement",
		"normal": "Normal",
		"easy": "Facile",
		"hard": "Difficile",
		"harder": "Plus Difficile",
		"insane": "InsensÃ©",
		"extreme": "ExtrÃªme",
		"demon": "DÃ©mon",
		"tutorial": "Tutoriel",
		"level": "Niveau",
		"coins": "PiÃ¨ces",
		"attempts": "Essais",
		"jumps": "Sauts",
		"deaths": "Morts",
		"time": "Temps",
		"best": "Record",
		"complete": "TerminÃ©",
		"level_complete": "Niveau TerminÃ© !",
		"level_failed": "Niveau RatÃ©",
		"new_best": "Nouveau Record !",
		"coins_collected": "PiÃ¨ces collectÃ©es",
		"secret_found": "Secret trouvÃ© !",
		"press_enter": "Appuyez sur EntrÃ©e",
		"tap_anywhere": "Touchez pour commencer",
		"loading": "Chargement",
		"paused": "Pause",
		"resume": "Reprendre",
		"restart": "Recommencer",
		"quit_to_menu": "Menu",
		"tap_to_restart": "Appuyez pour recommencer",
		"checkpoint_reached": "Checkpoint !",
		"practice_mode": "Mode EntraÃ®nement",
		"auto_retry": "RÃ©essai auto",
		"ghost_mode": "Mode fantÃ´me",
		"show_fps": "Afficher FPS",
		"screen_shake": "Secousse d'Ã©cran",
		"background_detail": "DÃ©tail du dÃ©cor",
		"particles": "Particules",
		"quality": "QualitÃ©",
		"quality_low": "Basse",
		"quality_medium": "Moyenne",
		"quality_high": "Haute",
		"vsync": "VSync",
		"fps_limit": "Limite de FPS",
		"fullscreen": "Plein Ã©cran",
		"resolution": "RÃ©solution",
		"master_volume": "Volume gÃ©nÃ©ral",
		"music_volume": "Volume musique",
		"sfx_volume": "Volume effets",
		"language": "Langue",
		"theme": "ThÃ¨me de couleurs",
		"controls": "ContrÃ´les",
		"rebind_jump": "Sauter",
		"rebind_pause": "Pause",
		"reset_controls": "RÃ©initialiser les contrÃ´les",
		"accessibility": "AccessibilitÃ©",
		"reduced_motion": "Mouvements rÃ©duits",
		"high_contrast": "Contraste Ã©levÃ©",
		"colorblind": "Mode daltonien",
		"ui_scale": "Ã‰chelle de l'interface",
		"statistics": "Statistiques",
		"stat.jumps": "Sauts totaux",
		"stat.deaths": "Morts totales",
		"stat.attempts": "Essais totaux",
		"stat.time": "Temps de jeu",
		"stat.levels": "Niveaux terminÃ©s",
		"stat.coins": "PiÃ¨ces collectÃ©es",
		"stat.secret_coins": "PiÃ¨ces secrÃ¨tes",
		"stat.endless": "Record infini",
		"stat.daily": "Record quotidien",
		"stat.achievements": "SuccÃ¨s",
		"achievements": "SuccÃ¨s",
		"achievements_progress": "{0} sur {1} dÃ©bloquÃ©s",
		"icon_shop": "Boutique d'icÃ´nes",
		"icon_color": "Couleur",
		"icon_trail": "TraÃ®nÃ©e",
		"buy": "Acheter",
		"equip": "Ã‰quiper",
		"owned": "PossÃ©dÃ©",
		"not_enough_coins": "Pas assez de piÃ¨ces",
		"custom_levels": "Niveaux PersonnalisÃ©s",
		"create_level": "CrÃ©er un Niveau",
		"play_custom": "Jouer",
		"edit": "Ã‰diter",
		"delete": "Supprimer",
		"delete_confirm": "Supprimer ce niveau ?",
		"editor": "Ã‰diteur de Niveaux",
		"editor.palette": "Objets",
		"editor.undo": "Annuler",
		"editor.redo": "RÃ©tablir",
		"editor.playtest": "Tester",
		"editor.save": "Sauvegarder",
		"editor.export": "Exporter",
		"editor.import": "Importer",
		"editor.grid": "Grille",
		"editor.layers": "Calques",
		"editor.trigger": "DÃ©clencheurs",
		"editor.search": "Rechercher",
		"editor.untitled": "Niveau sans titre",
		"editor.name": "Nom du niveau",
		"editor.music": "Musique",
		"editor.theme": "ThÃ¨me",
		"editor.difficulty": "DifficultÃ©",
		"editor.saved": "Niveau sauvegardÃ©",
		"editor.exported": "Niveau copiÃ© dans le presse-papiers",
		"editor.imported": "Niveau importÃ©",
		"editor.start_pos": "Position de dÃ©part",
		"editor.clear": "Vider",
		"editor.clear_confirm": "Vider tout le niveau ?",
		"daily": "DÃ©fi Quotidien",
		"daily.desc": "Un nouveau niveau chaque jour. Identique pour tous !",
		"daily.done": "DÃ©fi terminÃ© ! Revenez demain.",
		"endless": "Mode Infini",
		"endless.desc": "Jusqu'oÃ¹ irez-vous ?",
		"endless.score": "Distance",
		"story": "Mode Histoire",
		"story.desc": "Suivez DEX sur le Circuit NÃ©on",
		"boss": "Boss",
		"boss.warning": "LE WARDEN VOUS ATTEND",
		"level_locked": "Terminez les niveaux prÃ©cÃ©dents",
		"leaderboard": "Classement",
		"leaderboard.local": "Records locaux",
		"leaderboard.global": "Global (bientÃ´t)",
		"best_time": "Meilleur temps",
		"practice_best": "Record entraÃ®nement",
		"replay": "Replay",
		"ghost_beaten": "Vous avez battu votre fantÃ´me !",
		"ghost_faster": "Le fantÃ´me est devant",
		"new_record": "Nouveau record !",
		"achievement_unlocked": "SuccÃ¨s dÃ©bloquÃ©",
		"skip": "Passer",
		"next": "Suivant",
		"story_text.1": "Bienvenue sur le Circuit NÃ©on.",
		"story_text.2": "Je suis DEX. C'est mon dash.",
		"story_text.3": "Chaque battement me porte.",
		"story_text.4": "Les portails courbent ma route. La gravitÃ© me trahit.",
		"story_text.5": "Les Wardens gardent les profondeurs.",
		"story_text.6": "Je les dÃ©passerai tous.",
		"story_text.7": "Le Circuit ne se termine jamais...",
		"story_text.8": "...et moi non plus.",
		"fps": "FPS",
		"progress": "Progression",
		"restart_confirm": "Recommencer le niveau ?",
		"quit_confirm": "Quitter vers le menu ?",
		"delete_save": "Supprimer la sauvegarde",
		"delete_save_confirm": "IrrÃ©versible. Supprimer toute la progression ?",
		"reset": "RÃ©initialiser",
		"version": "Version",
		"controls_hint": "Espace / W / Haut - sauter | Ã‰chap - pause | R - recommencer",
		"how_to_play": "Maintenez pour sauter plus haut. Atterrissez pour tourner. Les portails changent tout.",
		"multilingual.credit": "Traductions contribuÃ©es par la communautÃ©.",
	},
	"pt": {
		"app.title": "DEX DASH",
		"app.tagline": "um plataforma rÃ­tmico",
		"menu.play": "Jogar",
		"menu.story": "HistÃ³ria",
		"menu.endless": "Infinito",
		"menu.daily": "DiÃ¡rio",
		"menu.editor": "Editor",
		"menu.custom": "NÃ­veis Personalizados",
		"menu.settings": "ConfiguraÃ§Ãµes",
		"menu.stats": "EstatÃ­sticas",
		"menu.achievements": "Conquistas",
		"menu.icons": "Ãcones",
		"menu.quit": "Sair",
		"menu.continue": "Continuar",
		"menu.level_select": "SeleÃ§Ã£o de NÃ­vel",
		"menu.main_menu": "Menu Principal",
		"back": "Voltar",
		"yes": "Sim",
		"no": "NÃ£o",
		"ok": "OK",
		"cancel": "Cancelar",
		"confirm": "Confirmar",
		"retry": "Tentar de novo",
		"continue": "Continuar",
		"play": "Jogar",
		"practice": "PrÃ¡tica",
		"normal": "Normal",
		"easy": "FÃ¡cil",
		"hard": "DifÃ­cil",
		"harder": "Mais DifÃ­cil",
		"insane": "Insano",
		"extreme": "Extremo",
		"demon": "DemÃ´nio",
		"tutorial": "Tutorial",
		"level": "NÃ­vel",
		"coins": "Moedas",
		"attempts": "Tentativas",
		"jumps": "Pulos",
		"deaths": "Mortes",
		"time": "Tempo",
		"best": "Recorde",
		"complete": "Completo",
		"level_complete": "NÃ­vel Completo!",
		"level_failed": "NÃ­vel Falhou",
		"new_best": "Novo Recorde!",
		"coins_collected": "Moedas coletadas",
		"secret_found": "Segredo encontrado!",
		"press_enter": "Pressione Enter",
		"tap_anywhere": "Toque para comeÃ§ar",
		"loading": "Carregando",
		"paused": "Pausado",
		"resume": "Continuar",
		"restart": "Reiniciar",
		"quit_to_menu": "Voltar ao Menu",
		"tap_to_restart": "Toque para reiniciar",
		"checkpoint_reached": "Checkpoint!",
		"practice_mode": "Modo PrÃ¡tica",
		"auto_retry": "Tentativa automÃ¡tica",
		"ghost_mode": "Modo fantasma",
		"show_fps": "Mostrar FPS",
		"screen_shake": "Tremor de tela",
		"background_detail": "Detalhe do fundo",
		"particles": "PartÃ­culas",
		"quality": "Qualidade",
		"quality_low": "Baixa",
		"quality_medium": "MÃ©dia",
		"quality_high": "Alta",
		"vsync": "VSync",
		"fps_limit": "Limite de FPS",
		"fullscreen": "Tela cheia",
		"resolution": "ResoluÃ§Ã£o",
		"master_volume": "Volume geral",
		"music_volume": "Volume da mÃºsica",
		"sfx_volume": "Volume dos efeitos",
		"language": "Idioma",
		"theme": "Tema de cores",
		"controls": "Controles",
		"rebind_jump": "Pular",
		"rebind_pause": "Pausa",
		"reset_controls": "Restaurar controles",
		"accessibility": "Acessibilidade",
		"reduced_motion": "Movimento reduzido",
		"high_contrast": "Alto contraste",
		"colorblind": "Modo daltÃ´nico",
		"ui_scale": "Escala da interface",
		"statistics": "EstatÃ­sticas",
		"stat.jumps": "Pulos totais",
		"stat.deaths": "Mortes totais",
		"stat.attempts": "Tentativas totais",
		"stat.time": "Tempo jogado",
		"stat.levels": "NÃ­veis concluÃ­dos",
		"stat.coins": "Moedas coletadas",
		"stat.secret_coins": "Moedas secretas",
		"stat.endless": "Recorde infinito",
		"stat.daily": "Recorde diÃ¡rio",
		"stat.achievements": "Conquistas",
		"achievements": "Conquistas",
		"achievements_progress": "{0} de {1} desbloqueadas",
		"icon_shop": "Loja de Ãcones",
		"icon_color": "Cor",
		"icon_trail": "Rastro",
		"buy": "Comprar",
		"equip": "Equipar",
		"owned": "Adquirido",
		"not_enough_coins": "Moedas insuficientes",
		"custom_levels": "NÃ­veis Personalizados",
		"create_level": "Criar NÃ­vel",
		"play_custom": "Jogar",
		"edit": "Editar",
		"delete": "Excluir",
		"delete_confirm": "Excluir este nÃ­vel?",
		"editor": "Editor de NÃ­veis",
		"editor.palette": "Objetos",
		"editor.undo": "Desfazer",
		"editor.redo": "Refazer",
		"editor.playtest": "Testar",
		"editor.save": "Salvar",
		"editor.export": "Exportar",
		"editor.import": "Importar",
		"editor.grid": "Grade",
		"editor.layers": "Camadas",
		"editor.trigger": "Gatilhos",
		"editor.search": "Buscar",
		"editor.untitled": "NÃ­vel sem tÃ­tulo",
		"editor.name": "Nome do nÃ­vel",
		"editor.music": "MÃºsica",
		"editor.theme": "Tema",
		"editor.difficulty": "Dificuldade",
		"editor.saved": "NÃ­vel salvo",
		"editor.exported": "NÃ­vel copiado para a Ã¡rea de transferÃªncia",
		"editor.imported": "NÃ­vel importado",
		"editor.start_pos": "PosiÃ§Ã£o inicial",
		"editor.clear": "Limpar",
		"editor.clear_confirm": "Limpar o nÃ­vel inteiro?",
		"daily": "Desafio DiÃ¡rio",
		"daily.desc": "Um novo nÃ­vel todo dia. Igual para todos!",
		"daily.done": "DiÃ¡rio concluÃ­do! Volte amanhÃ£.",
		"endless": "Modo Infinito",
		"endless.desc": "AtÃ© onde vocÃª consegue ir?",
		"endless.score": "DistÃ¢ncia",
		"story": "Modo HistÃ³ria",
		"story.desc": "Siga DEX no Circuito Neon",
		"boss": "Chefe",
		"boss.warning": "O WARDEN O AGUARDA",
		"level_locked": "Conclua os nÃ­veis anteriores",
		"leaderboard": "ClassificaÃ§Ã£o",
		"leaderboard.local": "Recordes locais",
		"leaderboard.global": "Global (em breve)",
		"best_time": "Melhor tempo",
		"practice_best": "Recorde de prÃ¡tica",
		"replay": "RepetiÃ§Ã£o",
		"ghost_beaten": "VocÃª superou seu fantasma!",
		"ghost_faster": "O fantasma estÃ¡ Ã  frente",
		"new_record": "Novo recorde!",
		"achievement_unlocked": "Conquista desbloqueada",
		"skip": "Pular",
		"next": "PrÃ³ximo",
		"story_text.1": "Bem-vindo ao Circuito Neon.",
		"story_text.2": "Eu sou DEX. Este Ã© meu dash.",
		"story_text.3": "Cada batida me leva adiante.",
		"story_text.4": "Portais curvam meu caminho. A gravidade me trai.",
		"story_text.5": "Os Wardens guardam as profundezas.",
		"story_text.6": "Vou superar todos eles.",
		"story_text.7": "O Circuito nunca termina...",
		"story_text.8": "...e eu tambÃ©m nÃ£o.",
		"fps": "FPS",
		"progress": "Progresso",
		"restart_confirm": "Reiniciar o nÃ­vel?",
		"quit_confirm": "Voltar ao menu?",
		"delete_save": "Apagar dados salvos",
		"delete_save_confirm": "Isso nÃ£o pode ser desfeito. Apagar tudo?",
		"reset": "Redefinir",
		"version": "VersÃ£o",
		"controls_hint": "EspaÃ§o / W / Cima - pular | Esc - pausa | R - reiniciar",
		"how_to_play": "Segure para pular mais alto. Aterrisse para girar. Portais mudam tudo.",
		"multilingual.credit": "TraduÃ§Ãµes contribuÃ­das pela comunidade.",
	},
	"ja": {
		"app.title": "DEX DASH",
		"app.tagline": "ãƒªã‚ºãƒ ãƒ—ãƒ©ãƒƒãƒˆãƒ•ã‚©ãƒ¼ãƒžãƒ¼",
		"menu.play": "ãƒ—ãƒ¬ã‚¤",
		"menu.story": "ã‚¹ãƒˆãƒ¼ãƒªãƒ¼",
		"menu.endless": "ã‚¨ãƒ³ãƒ‰ãƒ¬ã‚¹",
		"menu.daily": "ãƒ‡ã‚¤ãƒªãƒ¼",
		"menu.editor": "ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼",
		"menu.custom": "ã‚«ã‚¹ã‚¿ãƒ ãƒ¬ãƒ™ãƒ«",
		"menu.settings": "è¨­å®š",
		"menu.stats": "çµ±è¨ˆ",
		"menu.achievements": "å®Ÿç¸¾",
		"menu.icons": "ã‚¢ã‚¤ã‚³ãƒ³",
		"menu.quit": "çµ‚äº†",
		"menu.continue": "ç¶šãã‹ã‚‰",
		"menu.level_select": "ãƒ¬ãƒ™ãƒ«é¸æŠž",
		"menu.main_menu": "ãƒ¡ã‚¤ãƒ³ãƒ¡ãƒ‹ãƒ¥ãƒ¼",
		"back": "æˆ»ã‚‹",
		"yes": "ã¯ã„",
		"no": "ã„ã„ãˆ",
		"ok": "OK",
		"cancel": "ã‚­ãƒ£ãƒ³ã‚»ãƒ«",
		"confirm": "ç¢ºèª",
		"retry": "ãƒªãƒˆãƒ©ã‚¤",
		"continue": "ç¶šã‘ã‚‹",
		"play": "ãƒ—ãƒ¬ã‚¤",
		"practice": "ç·´ç¿’",
		"normal": "ãƒŽãƒ¼ãƒžãƒ«",
		"easy": "ã‚¤ãƒ¼ã‚¸ãƒ¼",
		"hard": "ãƒãƒ¼ãƒ‰",
		"harder": "ãƒãƒ¼ãƒ€ãƒ¼",
		"insane": "ã‚¤ãƒ³ã‚»ã‚¤ãƒ³",
		"extreme": "ã‚¨ã‚¯ã‚¹ãƒˆãƒªãƒ¼ãƒ ",
		"demon": "ãƒ‡ãƒ¼ãƒ¢ãƒ³",
		"tutorial": "ãƒãƒ¥ãƒ¼ãƒˆãƒªã‚¢ãƒ«",
		"level": "ãƒ¬ãƒ™ãƒ«",
		"coins": "ã‚³ã‚¤ãƒ³",
		"attempts": "æŒ‘æˆ¦å›žæ•°",
		"jumps": "ã‚¸ãƒ£ãƒ³ãƒ—",
		"deaths": "æ­»äº¡",
		"time": "æ™‚é–“",
		"best": "ãƒ™ã‚¹ãƒˆ",
		"complete": "é”æˆ",
		"level_complete": "ãƒ¬ãƒ™ãƒ«ã‚¯ãƒªã‚¢ï¼",
		"level_failed": "ãƒ¬ãƒ™ãƒ«å¤±æ•—",
		"new_best": "æ–°è¨˜éŒ²ï¼",
		"coins_collected": "ã‚³ã‚¤ãƒ³ç²å¾—",
		"secret_found": "ã‚·ãƒ¼ã‚¯ãƒ¬ãƒƒãƒˆç™ºè¦‹ï¼",
		"press_enter": "Enterã‚’æŠ¼ã™",
		"tap_anywhere": "ã‚¿ãƒƒãƒ—ã—ã¦é–‹å§‹",
		"loading": "èª­ã¿è¾¼ã¿ä¸­",
		"paused": "ä¸€æ™‚åœæ­¢",
		"resume": "å†é–‹",
		"restart": "ã‚„ã‚Šç›´ã™",
		"quit_to_menu": "ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã¸",
		"tap_to_restart": "???????",
		"checkpoint_reached": "ãƒã‚§ãƒƒã‚¯ãƒã‚¤ãƒ³ãƒˆï¼",
		"practice_mode": "ç·´ç¿’ãƒ¢ãƒ¼ãƒ‰",
		"auto_retry": "è‡ªå‹•ãƒªãƒˆãƒ©ã‚¤",
		"ghost_mode": "ã‚´ãƒ¼ã‚¹ãƒˆãƒ¢ãƒ¼ãƒ‰",
		"show_fps": "FPSè¡¨ç¤º",
		"screen_shake": "ç”»é¢æŒ¯å‹•",
		"background_detail": "èƒŒæ™¯ã®è©³ç´°",
		"particles": "ãƒ‘ãƒ¼ãƒ†ã‚£ã‚¯ãƒ«",
		"quality": "å“è³ª",
		"quality_low": "ä½Ž",
		"quality_medium": "ä¸­",
		"quality_high": "é«˜",
		"vsync": "VSync",
		"fps_limit": "FPSä¸Šé™",
		"fullscreen": "å…¨ç”»é¢",
		"resolution": "è§£åƒåº¦",
		"master_volume": "ãƒžã‚¹ã‚¿ãƒ¼ãƒœãƒªãƒ¥ãƒ¼ãƒ ",
		"music_volume": "éŸ³æ¥½",
		"sfx_volume": "åŠ¹æžœéŸ³",
		"language": "è¨€èªž",
		"theme": "ã‚«ãƒ©ãƒ¼ãƒ†ãƒ¼ãƒž",
		"controls": "ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ«",
		"rebind_jump": "ã‚¸ãƒ£ãƒ³ãƒ—",
		"rebind_pause": "ä¸€æ™‚åœæ­¢",
		"reset_controls": "ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ«ã‚’ãƒªã‚»ãƒƒãƒˆ",
		"accessibility": "ã‚¢ã‚¯ã‚»ã‚·ãƒ“ãƒªãƒ†ã‚£",
		"reduced_motion": "å‹•ãã‚’æ¸›ã‚‰ã™",
		"high_contrast": "é«˜ã‚³ãƒ³ãƒˆãƒ©ã‚¹ãƒˆ",
		"colorblind": "è‰²è¦šãƒ¢ãƒ¼ãƒ‰",
		"ui_scale": "UIã‚¹ã‚±ãƒ¼ãƒ«",
		"statistics": "çµ±è¨ˆ",
		"stat.jumps": "ç·ã‚¸ãƒ£ãƒ³ãƒ—å›žæ•°",
		"stat.deaths": "ç·æ­»äº¡å›žæ•°",
		"stat.attempts": "ç·æŒ‘æˆ¦å›žæ•°",
		"stat.time": "ãƒ—ãƒ¬ã‚¤æ™‚é–“",
		"stat.levels": "ã‚¯ãƒªã‚¢æ•°",
		"stat.coins": "ã‚³ã‚¤ãƒ³ç²å¾—",
		"stat.secret_coins": "ã‚·ãƒ¼ã‚¯ãƒ¬ãƒƒãƒˆã‚³ã‚¤ãƒ³",
		"stat.endless": "ã‚¨ãƒ³ãƒ‰ãƒ¬ã‚¹è¨˜éŒ²",
		"stat.daily": "ãƒ‡ã‚¤ãƒªãƒ¼è¨˜éŒ²",
		"stat.achievements": "å®Ÿç¸¾",
		"achievements": "å®Ÿç¸¾",
		"achievements_progress": "{0}/{1} è§£é™¤æ¸ˆã¿",
		"icon_shop": "ã‚¢ã‚¤ã‚³ãƒ³ã‚·ãƒ§ãƒƒãƒ—",
		"icon_color": "ã‚«ãƒ©ãƒ¼",
		"icon_trail": "ãƒˆãƒ¬ã‚¤ãƒ«",
		"buy": "è³¼å…¥",
		"equip": "è£…å‚™",
		"owned": "æ‰€æœ‰",
		"not_enough_coins": "ã‚³ã‚¤ãƒ³ãŒè¶³ã‚Šã¾ã›ã‚“",
		"custom_levels": "ã‚«ã‚¹ã‚¿ãƒ ãƒ¬ãƒ™ãƒ«",
		"create_level": "ãƒ¬ãƒ™ãƒ«ä½œæˆ",
		"play_custom": "ãƒ—ãƒ¬ã‚¤",
		"edit": "ç·¨é›†",
		"delete": "å‰Šé™¤",
		"delete_confirm": "ã“ã®ãƒ¬ãƒ™ãƒ«ã‚’å‰Šé™¤ã—ã¾ã™ã‹ï¼Ÿ",
		"editor": "ãƒ¬ãƒ™ãƒ«ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼",
		"editor.palette": "ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆ",
		"editor.undo": "å…ƒã«æˆ»ã™",
		"editor.redo": "ã‚„ã‚Šç›´ã™",
		"editor.playtest": "ãƒ†ã‚¹ãƒˆãƒ—ãƒ¬ã‚¤",
		"editor.save": "ä¿å­˜",
		"editor.export": "ã‚¨ã‚¯ã‚¹ãƒãƒ¼ãƒˆ",
		"editor.import": "ã‚¤ãƒ³ãƒãƒ¼ãƒˆ",
		"editor.grid": "ã‚°ãƒªãƒƒãƒ‰",
		"editor.layers": "ãƒ¬ã‚¤ãƒ¤ãƒ¼",
		"editor.trigger": "ãƒˆãƒªã‚¬ãƒ¼",
		"editor.search": "æ¤œç´¢",
		"editor.untitled": "ç„¡é¡Œã®ãƒ¬ãƒ™ãƒ«",
		"editor.name": "ãƒ¬ãƒ™ãƒ«å",
		"editor.music": "éŸ³æ¥½",
		"editor.theme": "ãƒ†ãƒ¼ãƒž",
		"editor.difficulty": "é›£æ˜“åº¦",
		"editor.saved": "ä¿å­˜ã—ã¾ã—ãŸ",
		"editor.exported": "ã‚¯ãƒªãƒƒãƒ—ãƒœãƒ¼ãƒ‰ã«ã‚³ãƒ”ãƒ¼",
		"editor.imported": "ã‚¤ãƒ³ãƒãƒ¼ãƒˆã—ã¾ã—ãŸ",
		"editor.start_pos": "ã‚¹ã‚¿ãƒ¼ãƒˆä½ç½®",
		"editor.clear": "ã‚¯ãƒªã‚¢",
		"editor.clear_confirm": "ãƒ¬ãƒ™ãƒ«å…¨ä½“ã‚’æ¶ˆåŽ»ã—ã¾ã™ã‹ï¼Ÿ",
		"daily": "ãƒ‡ã‚¤ãƒªãƒ¼ãƒãƒ£ãƒ¬ãƒ³ã‚¸",
		"daily.desc": "æ¯Žæ—¥æ–°ã—ã„ãƒ¬ãƒ™ãƒ«ã€‚ã¿ã‚“ãªåŒã˜ï¼",
		"daily.done": "ãƒ‡ã‚¤ãƒªãƒ¼é”æˆï¼ã¾ãŸæ˜Žæ—¥ï¼",
		"endless": "ã‚¨ãƒ³ãƒ‰ãƒ¬ã‚¹ãƒ¢ãƒ¼ãƒ‰",
		"endless.desc": "ã©ã“ã¾ã§è¡Œã‘ã‚‹ï¼Ÿ",
		"endless.score": "è·é›¢",
		"story": "ã‚¹ãƒˆãƒ¼ãƒªãƒ¼ãƒ¢ãƒ¼ãƒ‰",
		"story.desc": "ãƒã‚ªãƒ³ã‚µãƒ¼ã‚­ãƒƒãƒˆã§DEXã‚’å°Žã‘",
		"boss": "ãƒœã‚¹",
		"boss.warning": "WARDENãŒå¾…ã¡æ§‹ãˆã¦ã„ã‚‹",
		"level_locked": "å‰ã®ãƒ¬ãƒ™ãƒ«ã‚’ã‚¯ãƒªã‚¢ã—ã‚ˆã†",
		"leaderboard": "ãƒªãƒ¼ãƒ€ãƒ¼ãƒœãƒ¼ãƒ‰",
		"leaderboard.local": "ãƒ­ãƒ¼ã‚«ãƒ«è¨˜éŒ²",
		"leaderboard.global": "ã‚°ãƒ­ãƒ¼ãƒãƒ«ï¼ˆè¿‘æ—¥å…¬é–‹ï¼‰",
		"best_time": "ãƒ™ã‚¹ãƒˆã‚¿ã‚¤ãƒ ",
		"practice_best": "ç·´ç¿’ãƒ™ã‚¹ãƒˆ",
		"replay": "ãƒªãƒ—ãƒ¬ã‚¤",
		"ghost_beaten": "ã‚´ãƒ¼ã‚¹ãƒˆã«å‹ã£ãŸï¼",
		"ghost_faster": "ã‚´ãƒ¼ã‚¹ãƒˆãŒå…ˆè¡Œä¸­",
		"new_record": "æ–°è¨˜éŒ²ï¼",
		"achievement_unlocked": "å®Ÿç¸¾è§£é™¤",
		"skip": "ã‚¹ã‚­ãƒƒãƒ—",
		"next": "æ¬¡ã¸",
		"story_text.1": "ãƒã‚ªãƒ³ã‚µãƒ¼ã‚­ãƒƒãƒˆã¸ã‚ˆã†ã“ãã€‚",
		"story_text.2": "ç§ã¯DEXã€‚ã“ã‚ŒãŒç§ã®ãƒ€ãƒƒã‚·ãƒ¥ã€‚",
		"story_text.3": "ãƒ“ãƒ¼ãƒˆãŒåƒ•ã‚’å‰ã«é‹ã¶ã€‚",
		"story_text.4": "ãƒãƒ¼ã‚¿ãƒ«ãŒé“ã‚’æ›²ã’ã‚‹ã€‚é‡åŠ›ã¯è£åˆ‡ã‚‹ã€‚",
		"story_text.5": "WARDENãŒæ·±å±¤ã‚’å®ˆã‚‹ã€‚",
		"story_text.6": "å…¨éƒ¨è¿½ã„æŠœã„ã¦ã‚„ã‚‹ã€‚",
		"story_text.7": "ã‚µãƒ¼ã‚­ãƒƒãƒˆã¯çµ‚ã‚ã‚‰ãªã„â€¦",
		"story_text.8": "â€¦åƒ•ã‚‚çµ‚ã‚ã‚‰ãªã„ã€‚",
		"fps": "FPS",
		"progress": "é€²æ—",
		"restart_confirm": "ãƒ¬ãƒ™ãƒ«ã‚’ã‚„ã‚Šç›´ã—ã¾ã™ã‹ï¼Ÿ",
		"quit_confirm": "ãƒ¡ãƒ‹ãƒ¥ãƒ¼ã«æˆ»ã‚Šã¾ã™ã‹ï¼Ÿ",
		"delete_save": "ã‚»ãƒ¼ãƒ–ãƒ‡ãƒ¼ã‚¿ã‚’å‰Šé™¤",
		"delete_save_confirm": "å…ƒã«æˆ»ã›ã¾ã›ã‚“ã€‚å…¨ã¦å‰Šé™¤ã—ã¾ã™ã‹ï¼Ÿ",
		"reset": "ãƒªã‚»ãƒƒãƒˆ",
		"version": "ãƒãƒ¼ã‚¸ãƒ§ãƒ³",
		"controls_hint": "ã‚¹ãƒšãƒ¼ã‚¹ / W / â†‘ - ã‚¸ãƒ£ãƒ³ãƒ— | Esc - ä¸€æ™‚åœæ­¢ | R - ãƒªã‚¹ã‚¿ãƒ¼ãƒˆ",
		"how_to_play": "é•·æŠ¼ã—ã§é«˜ãã‚¸ãƒ£ãƒ³ãƒ—ã€‚ç€åœ°ã§å›žè»¢ã€‚ãƒãƒ¼ã‚¿ãƒ«ãŒå…¨ã¦ã‚’å¤‰ãˆã‚‹ã€‚",
		"multilingual.credit": "ç¿»è¨³ã¯ã‚³ãƒŸãƒ¥ãƒ‹ãƒ†ã‚£ã«ã‚ˆã‚‹ã‚‚ã®ã§ã™ã€‚",
	},
}
