extends Node
## Localization - lightweight string table with runtime language switching.

signal language_changed(lang: String)

const LANGS := ["en", "es", "de", "fr", "pt", "ja"]

var lang := "en"
var _table: Dictionary = {}


func _ready() -> void:
	lang = str(SettingsManager.get_ui("language"))
	if not LANGS.has(lang):
		lang = "en"
	load_table(lang)


func load_table(code: String) -> void:
	_table = TABLES.get(code, TABLES["en"])
	lang = code
	SettingsManager.set_ui("language", code)
	language_changed.emit(code)


func set_language(code: String) -> void:
	if not LANGS.has(code):
		return
	load_table(code)


func t(key: String) -> String:
	return str(_table.get(key, TABLES["en"].get(key, key)))


func trf(key: String, args: Array) -> String:
	var s := t(key)
	for i in args.size():
		s = s.replace("{%d}" % i, str(args[i]))
	return s


const TABLES := {
	"en": {
		"app.title": "DEX DASH",
		"app.tagline": "a rhythm platformer",
		"menu.play": "Play",
		"menu.story": "Story",
		"menu.endless": "Endless",
		"menu.daily": "Daily",
		"menu.editor": "Editor",
		"menu.custom": "Custom Levels",
		"menu.settings": "Settings",
		"menu.stats": "Statistics",
		"menu.achievements": "Achievements",
		"menu.icons": "Icons",
		"menu.quit": "Quit",
		"menu.continue": "Continue",
		"menu.level_select": "Level Select",
		"menu.main_menu": "Main Menu",
		"menu.modes": "Game Modes",
		"back": "Back",
		"yes": "Yes",
		"no": "No",
		"ok": "OK",
		"cancel": "Cancel",
		"confirm": "Confirm",
		"retry": "Retry",
		"continue": "Continue",
		"play": "Play",
		"practice": "Practice",
		"normal": "Normal",
		"easy": "Easy",
		"hard": "Hard",
		"harder": "Harder",
		"insane": "Insane",
		"extreme": "Extreme",
		"demon": "Demon",
		"tutorial": "Tutorial",
		"level": "Level",
		"coins": "Coins",
		"attempts": "Attempts",
		"jumps": "Jumps",
		"deaths": "Deaths",
		"time": "Time",
		"best": "Best",
		"complete": "Complete",
		"level_complete": "Level Complete!",
		"level_failed": "Level Failed",
		"new_best": "New Best!",
		"coins_collected": "Coins collected",
		"secret_found": "Secret found!",
		"press_enter": "Press Enter",
		"tap_anywhere": "Tap anywhere to start",
		"loading": "Loading",
		"paused": "Paused",
		"resume": "Resume",
		"restart": "Restart",
		"quit_to_menu": "Quit to Menu",
		"checkpoint_reached": "Checkpoint!",
		"practice_mode": "Practice Mode",
		"auto_retry": "Auto retry",
		"ghost_mode": "Ghost mode",
		"show_fps": "Show FPS",
		"screen_shake": "Screen shake",
		"background_detail": "Background detail",
		"particles": "Particles",
		"quality": "Quality",
		"quality_low": "Low",
		"quality_medium": "Medium",
		"quality_high": "High",
		"vsync": "VSync",
		"fps_limit": "FPS limit",
		"fullscreen": "Fullscreen",
		"resolution": "Resolution",
		"master_volume": "Master volume",
		"music_volume": "Music volume",
		"sfx_volume": "SFX volume",
		"language": "Language",
		"theme": "Color theme",
		"controls": "Controls",
		"rebind_jump": "Jump",
		"rebind_pause": "Pause",
		"reset_controls": "Reset controls",
		"accessibility": "Accessibility",
		"reduced_motion": "Reduced motion",
		"high_contrast": "High contrast",
		"colorblind": "Colorblind mode",
		"ui_scale": "UI scale",
		"statistics": "Statistics",
		"stat.jumps": "Total jumps",
		"stat.deaths": "Total deaths",
		"stat.attempts": "Total attempts",
		"stat.time": "Time played",
		"stat.levels": "Levels completed",
		"stat.coins": "Coins collected",
		"stat.secret_coins": "Secret coins",
		"stat.endless": "Endless best",
		"stat.daily": "Daily best",
		"stat.achievements": "Achievements",
		"achievements": "Achievements",
		"achievements_progress": "Unlocked {0} of {1}",
		"icon_shop": "Icon Shop",
		"icon_color": "Color",
		"icon_trail": "Trail",
		"buy": "Buy",
		"equip": "Equip",
		"owned": "Owned",
		"not_enough_coins": "Not enough coins",
		"custom_levels": "Custom Levels",
		"create_level": "Create Level",
		"play_custom": "Play",
		"edit": "Edit",
		"delete": "Delete",
		"delete_confirm": "Delete this level?",
		"editor": "Level Editor",
		"editor.palette": "Objects",
		"editor.undo": "Undo",
		"editor.redo": "Redo",
		"editor.playtest": "Playtest",
		"editor.save": "Save",
		"editor.export": "Export",
		"editor.import": "Import",
		"editor.grid": "Grid",
		"editor.layers": "Layers",
		"editor.trigger": "Triggers",
		"editor.search": "Search",
		"editor.untitled": "Untitled Level",
		"editor.name": "Level name",
		"editor.music": "Music",
		"editor.theme": "Theme",
		"editor.difficulty": "Difficulty",
		"editor.saved": "Level saved",
		"editor.exported": "Level copied to clipboard",
		"editor.imported": "Level imported",
		"editor.start_pos": "Start position",
		"editor.clear": "Clear",
		"editor.clear_confirm": "Clear the entire level?",
		"daily": "Daily Challenge",
		"daily.desc": "A new level every day. Same for everyone!",
		"daily.done": "Daily completed! Come back tomorrow.",
		"endless": "Endless Mode",
		"endless.desc": "How far can you go?",
		"endless.score": "Distance",
		"story": "Story Mode",
		"story.desc": "Follow DEX on the Neon Circuit",
		"boss": "Boss",
		"boss.warning": "THE WARDEN AWAITS",
		"level_locked": "Complete previous levels to unlock",
		"leaderboard": "Leaderboard",
		"leaderboard.local": "Local bests",
		"leaderboard.global": "Global (coming soon)",
		"best_time": "Best time",
		"practice_best": "Practice best",
		"replay": "Replay",
		"ghost_beaten": "You beat your ghost!",
		"ghost_faster": "Ghost is still ahead",
		"new_record": "New record!",
		"achievement_unlocked": "Achievement unlocked",
		"skip": "Skip",
		"next": "Next",
		"story_text.1": "Welcome to the Neon Circuit.",
		"story_text.2": "I am DEX. This is my dash.",
		"story_text.3": "Every beat carries me forward.",
		"story_text.4": "Portals bend my path. Gravity betrays me.",
		"story_text.5": "The Wardens guard the depths.",
		"story_text.6": "I will outrun them all.",
		"story_text.7": "The Circuit never ends...",
		"story_text.8": "...and neither do I.",
		"fps": "FPS",
		"progress": "Progress",
		"restart_confirm": "Restart the level?",
		"quit_confirm": "Quit to menu?",
		"delete_save": "Delete save data",
		"delete_save_confirm": "This cannot be undone. Delete all progress?",
		"reset": "Reset",
		"version": "Version",
		"controls_hint": "Space / W / Up - jump | Esc - pause | R - restart",
		"how_to_play": "Hold to jump higher. Land to flip. Portals change everything.",
		"multilingual.credit": "Translations are community-contributed.",
	},
	"es": {
		"app.title": "DEX DASH",
		"app.tagline": "un plataformer ritmico",
		"menu.play": "Jugar",
		"menu.story": "Historia",
		"menu.endless": "Infinito",
		"menu.daily": "Diario",
		"menu.editor": "Editor",
		"menu.custom": "Niveles Personalizados",
		"menu.settings": "Ajustes",
		"menu.stats": "Estadisticas",
		"menu.achievements": "Logros",
		"menu.icons": "Iconos",
		"menu.quit": "Salir",
		"menu.continue": "Continuar",
		"menu.level_select": "Seleccion de Nivel",
		"menu.main_menu": "Menu Principal",
		"back": "Volver",
		"yes": "Si",
		"no": "No",
		"ok": "OK",
		"cancel": "Cancelar",
		"confirm": "Confirmar",
		"retry": "Reintentar",
		"continue": "Continuar",
		"play": "Jugar",
		"practice": "Practica",
		"normal": "Normal",
		"easy": "Facil",
		"hard": "Dificil",
		"harder": "Mas Dificil",
		"insane": "Insano",
		"extreme": "Extremo",
		"demon": "Demonio",
		"tutorial": "Tutorial",
		"level": "Nivel",
		"coins": "Monedas",
		"attempts": "Intentos",
		"jumps": "Saltos",
		"deaths": "Muertes",
		"time": "Tiempo",
		"best": "Mejor",
		"complete": "Completado",
		"level_complete": "Nivel Completado!",
		"level_failed": "Nivel Fallido",
		"new_best": "Nuevo Record!",
		"coins_collected": "Monedas recogidas",
		"secret_found": "Secreto encontrado!",
		"press_enter": "Pulsa Enter",
		"tap_anywhere": "Toca en cualquier lugar para empezar",
		"loading": "Cargando",
		"paused": "Pausado",
		"resume": "Reanudar",
		"restart": "Reiniciar",
		"quit_to_menu": "Salir al Menu",
		"checkpoint_reached": "Punto de control!",
		"practice_mode": "Modo Practica",
		"auto_retry": "Reintento automatico",
		"ghost_mode": "Modo fantasma",
		"show_fps": "Mostrar FPS",
		"screen_shake": "Sacudida de pantalla",
		"background_detail": "Detalle de fondo",
		"particles": "Particulas",
		"quality": "Calidad",
		"quality_low": "Baja",
		"quality_medium": "Media",
		"quality_high": "Alta",
		"vsync": "VSync",
		"fps_limit": "Limite de FPS",
		"fullscreen": "Pantalla completa",
		"resolution": "Resolucion",
		"master_volume": "Volumen general",
		"music_volume": "Volumen musica",
		"sfx_volume": "Volumen efectos",
		"language": "Idioma",
		"theme": "Tema de color",
		"controls": "Controles",
		"rebind_jump": "Saltar",
		"rebind_pause": "Pausa",
		"reset_controls": "Restablecer controles",
		"accessibility": "Accesibilidad",
		"reduced_motion": "Movimiento reducido",
		"high_contrast": "Alto contraste",
		"colorblind": "Modo daltonico",
		"ui_scale": "Escala de interfaz",
		"statistics": "Estadisticas",
		"stat.jumps": "Saltos totales",
		"stat.deaths": "Muertes totales",
		"stat.attempts": "Intentos totales",
		"stat.time": "Tiempo jugado",
		"stat.levels": "Niveles completados",
		"stat.coins": "Monedas recogidas",
		"stat.secret_coins": "Monedas secretas",
		"stat.endless": "Mejor en infinito",
		"stat.daily": "Mejor diario",
		"stat.achievements": "Logros",
		"achievements": "Logros",
		"achievements_progress": "Desbloqueados {0} de {1}",
		"icon_shop": "Tienda de Iconos",
		"icon_color": "Color",
		"icon_trail": "Estela",
		"buy": "Comprar",
		"equip": "Equipar",
		"owned": "Adquirido",
		"not_enough_coins": "Monedas insuficientes",
		"custom_levels": "Niveles Personalizados",
		"create_level": "Crear Nivel",
		"play_custom": "Jugar",
		"edit": "Editar",
		"delete": "Borrar",
		"delete_confirm": "Borrar este nivel?",
		"editor": "Editor de Niveles",
		"editor.palette": "Objetos",
		"editor.undo": "Deshacer",
		"editor.redo": "Rehacer",
		"editor.playtest": "Probar",
		"editor.save": "Guardar",
		"editor.export": "Exportar",
		"editor.import": "Importar",
		"editor.grid": "Cuadricula",
		"editor.layers": "Capas",
		"editor.trigger": "Disparadores",
		"editor.search": "Buscar",
		"editor.untitled": "Nivel sin titulo",
		"editor.name": "Nombre del nivel",
		"editor.music": "Musica",
		"editor.theme": "Tema",
		"editor.difficulty": "Dificultad",
		"editor.saved": "Nivel guardado",
		"editor.exported": "Nivel copiado al portapapeles",
		"editor.imported": "Nivel importado",
		"editor.start_pos": "Posicion inicial",
		"editor.clear": "Limpiar",
		"editor.clear_confirm": "Limpiar todo el nivel?",
		"daily": "Desafio Diario",
		"daily.desc": "Un nivel nuevo cada dia. Igual para todos!",
		"daily.done": "Diario completado! Vuelve manana.",
		"endless": "Modo Infinito",
		"endless.desc": "Hasta donde puedes llegar?",
		"endless.score": "Distancia",
		"story": "Modo Historia",
		"story.desc": "Acompania a DEX en el Circuito Neon",
		"boss": "Jefe",
		"boss.warning": "EL GUARDIAN TE ESPERA",
		"level_locked": "Completa niveles anteriores para desbloquear",
		"leaderboard": "Clasificacion",
		"leaderboard.local": "Mejores locales",
		"leaderboard.global": "Global (proximamente)",
		"best_time": "Mejor tiempo",
		"practice_best": "Mejor en practica",
		"replay": "Repeticion",
		"ghost_beaten": "Has superado a tu fantasma!",
		"ghost_faster": "El fantasma sigue adelante",
		"new_record": "Nuevo record!",
		"achievement_unlocked": "Logro desbloqueado",
		"skip": "Saltar",
		"next": "Siguiente",
		"story_text.1": "Bienvenido al Circuito Neon.",
		"story_text.2": "Soy DEX. Esta es mi carrera.",
		"story_text.3": "Cada ritmo me impulsa.",
		"story_text.4": "Los portales tuercen mi camino. La gravedad me traiciona.",
		"story_text.5": "Los Guardianes custodian las profundidades.",
		"story_text.6": "Les superare a todos.",
		"story_text.7": "El Circuito nunca termina...",
		"story_text.8": "...y yo tampoco.",
		"fps": "FPS",
		"progress": "Progreso",
		"restart_confirm": "Reiniciar el nivel?",
		"quit_confirm": "Salir al menu?",
		"delete_save": "Borrar datos guardados",
		"delete_save_confirm": "Esto no se puede deshacer. Borrar todo el progreso?",
		"reset": "Reiniciar",
		"version": "Version",
		"controls_hint": "Espacio / W / Arriba - saltar | Esc - pausa | R - reiniciar",
		"how_to_play": "Mantener para saltar mas alto. Aterriza para girar. Los portales lo cambian todo.",
		"multilingual.credit": "Las traducciones son aportadas por la comunidad.",
	},
	"de": {
		"app.title": "DEX DASH",
		"app.tagline": "ein Rhythmus-Platformer",
		"menu.play": "Spielen",
		"menu.story": "Story",
		"menu.endless": "Endlos",
		"menu.daily": "Täglich",
		"menu.editor": "Editor",
		"menu.custom": "Eigene Level",
		"menu.settings": "Einstellungen",
		"menu.stats": "Statistiken",
		"menu.achievements": "Errungenschaften",
		"menu.icons": "Icons",
		"menu.quit": "Beenden",
		"menu.continue": "Weiter",
		"menu.level_select": "Levelauswahl",
		"menu.main_menu": "Hauptmenü",
		"back": "Zurück",
		"yes": "Ja",
		"no": "Nein",
		"ok": "OK",
		"cancel": "Abbrechen",
		"confirm": "Bestätigen",
		"retry": "Erneut",
		"continue": "Weiter",
		"play": "Spielen",
		"practice": "Übung",
		"normal": "Normal",
		"easy": "Leicht",
		"hard": "Schwer",
		"harder": "Schwerer",
		"insane": "Irrsinnig",
		"extreme": "Extrem",
		"demon": "Dämon",
		"tutorial": "Tutorial",
		"level": "Level",
		"coins": "Münzen",
		"attempts": "Versuche",
		"jumps": "Sprünge",
		"deaths": "Tode",
		"time": "Zeit",
		"best": "Best",
		"complete": "Abschließen",
		"level_complete": "Level Geschafft!",
		"level_failed": "Level Fehlgeschlagen",
		"new_best": "Neuer Rekord!",
		"coins_collected": "Münzen gesammelt",
		"secret_found": "Geheimnis gefunden!",
		"press_enter": "Enter drücken",
		"tap_anywhere": "Zum Starten tippen",
		"loading": "Laden",
		"paused": "Pausiert",
		"resume": "Weiterspielen",
		"restart": "Neustart",
		"quit_to_menu": "Zum Menü",
		"checkpoint_reached": "Kontrollpunkt!",
		"practice_mode": "Übungsmodus",
		"auto_retry": "Auto-Wiederholung",
		"ghost_mode": "Geistermodus",
		"show_fps": "FPS anzeigen",
		"screen_shake": "Bildschirm wackeln",
		"background_detail": "Hintergrunddetails",
		"particles": "Partikel",
		"quality": "Qualität",
		"quality_low": "Niedrig",
		"quality_medium": "Mittel",
		"quality_high": "Hoch",
		"vsync": "VSync",
		"fps_limit": "FPS-Limit",
		"fullscreen": "Vollbild",
		"resolution": "Auflösung",
		"master_volume": "Hauptlautstärke",
		"music_volume": "Musiklautstärke",
		"sfx_volume": "Effektlautstärke",
		"language": "Sprache",
		"theme": "Farbschema",
		"controls": "Steuerung",
		"rebind_jump": "Springen",
		"rebind_pause": "Pause",
		"reset_controls": "Steuerung zurücksetzen",
		"accessibility": "Barrierefreiheit",
		"reduced_motion": "Reduzierte Bewegung",
		"high_contrast": "Hoher Kontrast",
		"colorblind": "Farbenblind-Modus",
		"ui_scale": "UI-Skalierung",
		"statistics": "Statistiken",
		"stat.jumps": "Sprünge gesamt",
		"stat.deaths": "Tode gesamt",
		"stat.attempts": "Versuche gesamt",
		"stat.time": "Spielzeit",
		"stat.levels": "Level abgeschlossen",
		"stat.coins": "Münzen gesammelt",
		"stat.secret_coins": "Geheimmünzen",
		"stat.endless": "Endlos-Rekord",
		"stat.daily": "Tages-Rekord",
		"stat.achievements": "Errungenschaften",
		"achievements": "Errungenschaften",
		"achievements_progress": "{0} von {1} freigeschaltet",
		"icon_shop": "Icon-Shop",
		"icon_color": "Farbe",
		"icon_trail": "Spur",
		"buy": "Kaufen",
		"equip": "Ausrüsten",
		"owned": "Besessen",
		"not_enough_coins": "Nicht genug Münzen",
		"custom_levels": "Eigene Level",
		"create_level": "Level erstellen",
		"play_custom": "Spielen",
		"edit": "Bearbeiten",
		"delete": "Löschen",
		"delete_confirm": "Dieses Level löschen?",
		"editor": "Level-Editor",
		"editor.palette": "Objekte",
		"editor.undo": "Rückgängig",
		"editor.redo": "Wiederholen",
		"editor.playtest": "Testen",
		"editor.save": "Speichern",
		"editor.export": "Exportieren",
		"editor.import": "Importieren",
		"editor.grid": "Raster",
		"editor.layers": "Ebenen",
		"editor.trigger": "Trigger",
		"editor.search": "Suchen",
		"editor.untitled": "Unbenanntes Level",
		"editor.name": "Levelname",
		"editor.music": "Musik",
		"editor.theme": "Thema",
		"editor.difficulty": "Schwierigkeit",
		"editor.saved": "Level gespeichert",
		"editor.exported": "Level in Zwischenablage kopiert",
		"editor.imported": "Level importiert",
		"editor.start_pos": "Startposition",
		"editor.clear": "Leeren",
		"editor.clear_confirm": "Ganzes Level leeren?",
		"daily": "Tages-Challenge",
		"daily.desc": "Jeden Tag ein neues Level. Für alle gleich!",
		"daily.done": "Tages-Challenge geschafft! Bis morgen.",
		"endless": "Endlosmodus",
		"endless.desc": "Wie weit kommst du?",
		"endless.score": "Distanz",
		"story": "Story-Modus",
		"story.desc": "Folge DEX auf dem Neon-Circuit",
		"boss": "Boss",
		"boss.warning": "DER WARDEN ERWARTET DICH",
		"level_locked": "Schließe vorherige Level ab",
		"leaderboard": "Bestenliste",
		"leaderboard.local": "Lokale Bestzeiten",
		"leaderboard.global": "Global (bald verfügbar)",
		"best_time": "Beste Zeit",
		"practice_best": "Übungs-Rekord",
		"replay": "Wiederholung",
		"ghost_beaten": "Du hast deinen Geist geschlagen!",
		"ghost_faster": "Der Geist ist noch vorn",
		"new_record": "Neuer Rekord!",
		"achievement_unlocked": "Errungenschaft freigeschaltet",
		"skip": "Überspringen",
		"next": "Weiter",
		"story_text.1": "Willkommen im Neon-Circuit.",
		"story_text.2": "Ich bin DEX. Das ist mein Dash.",
		"story_text.3": "Jeder Beat trägt mich voran.",
		"story_text.4": "Portale verbiegen meinen Weg. Schwerkraft betrügt mich.",
		"story_text.5": "Die Wardens bewachen die Tiefen.",
		"story_text.6": "Ich werde sie alle überholen.",
		"story_text.7": "Der Circuit endet nie...",
		"story_text.8": "...und ich auch nicht.",
		"fps": "FPS",
		"progress": "Fortschritt",
		"restart_confirm": "Level neu starten?",
		"quit_confirm": "Zum Menü?",
		"delete_save": "Spielstand löschen",
		"delete_save_confirm": "Das kann nicht rückgängig gemacht werden. Alles löschen?",
		"reset": "Zurücksetzen",
		"version": "Version",
		"controls_hint": "Leertaste / W / Hoch - springen | Esc - Pause | R - Neustart",
		"how_to_play": "Halten für höhere Sprünge. Landen zum Drehen. Portale ändern alles.",
		"multilingual.credit": "Übersetzungen stammen aus der Community.",
	},
	"fr": {
		"app.title": "DEX DASH",
		"app.tagline": "un platformer rythmique",
		"menu.play": "Jouer",
		"menu.story": "Histoire",
		"menu.endless": "Infini",
		"menu.daily": "Quotidien",
		"menu.editor": "Éditeur",
		"menu.custom": "Niveaux Perso",
		"menu.settings": "Réglages",
		"menu.stats": "Statistiques",
		"menu.achievements": "Succès",
		"menu.icons": "Icônes",
		"menu.quit": "Quitter",
		"menu.continue": "Continuer",
		"menu.level_select": "Sélection de Niveaux",
		"menu.main_menu": "Menu Principal",
		"back": "Retour",
		"yes": "Oui",
		"no": "Non",
		"ok": "OK",
		"cancel": "Annuler",
		"confirm": "Confirmer",
		"retry": "Réessayer",
		"continue": "Continuer",
		"play": "Jouer",
		"practice": "Entraînement",
		"normal": "Normal",
		"easy": "Facile",
		"hard": "Difficile",
		"harder": "Plus Difficile",
		"insane": "Insensé",
		"extreme": "Extrême",
		"demon": "Démon",
		"tutorial": "Tutoriel",
		"level": "Niveau",
		"coins": "Pièces",
		"attempts": "Essais",
		"jumps": "Sauts",
		"deaths": "Morts",
		"time": "Temps",
		"best": "Record",
		"complete": "Terminé",
		"level_complete": "Niveau Terminé !",
		"level_failed": "Niveau Raté",
		"new_best": "Nouveau Record !",
		"coins_collected": "Pièces collectées",
		"secret_found": "Secret trouvé !",
		"press_enter": "Appuyez sur Entrée",
		"tap_anywhere": "Touchez pour commencer",
		"loading": "Chargement",
		"paused": "Pause",
		"resume": "Reprendre",
		"restart": "Recommencer",
		"quit_to_menu": "Menu",
		"checkpoint_reached": "Checkpoint !",
		"practice_mode": "Mode Entraînement",
		"auto_retry": "Réessai auto",
		"ghost_mode": "Mode fantôme",
		"show_fps": "Afficher FPS",
		"screen_shake": "Secousse d'écran",
		"background_detail": "Détail du décor",
		"particles": "Particules",
		"quality": "Qualité",
		"quality_low": "Basse",
		"quality_medium": "Moyenne",
		"quality_high": "Haute",
		"vsync": "VSync",
		"fps_limit": "Limite de FPS",
		"fullscreen": "Plein écran",
		"resolution": "Résolution",
		"master_volume": "Volume général",
		"music_volume": "Volume musique",
		"sfx_volume": "Volume effets",
		"language": "Langue",
		"theme": "Thème de couleurs",
		"controls": "Contrôles",
		"rebind_jump": "Sauter",
		"rebind_pause": "Pause",
		"reset_controls": "Réinitialiser les contrôles",
		"accessibility": "Accessibilité",
		"reduced_motion": "Mouvements réduits",
		"high_contrast": "Contraste élevé",
		"colorblind": "Mode daltonien",
		"ui_scale": "Échelle de l'interface",
		"statistics": "Statistiques",
		"stat.jumps": "Sauts totaux",
		"stat.deaths": "Morts totales",
		"stat.attempts": "Essais totaux",
		"stat.time": "Temps de jeu",
		"stat.levels": "Niveaux terminés",
		"stat.coins": "Pièces collectées",
		"stat.secret_coins": "Pièces secrètes",
		"stat.endless": "Record infini",
		"stat.daily": "Record quotidien",
		"stat.achievements": "Succès",
		"achievements": "Succès",
		"achievements_progress": "{0} sur {1} débloqués",
		"icon_shop": "Boutique d'icônes",
		"icon_color": "Couleur",
		"icon_trail": "Traînée",
		"buy": "Acheter",
		"equip": "Équiper",
		"owned": "Possédé",
		"not_enough_coins": "Pas assez de pièces",
		"custom_levels": "Niveaux Personnalisés",
		"create_level": "Créer un Niveau",
		"play_custom": "Jouer",
		"edit": "Éditer",
		"delete": "Supprimer",
		"delete_confirm": "Supprimer ce niveau ?",
		"editor": "Éditeur de Niveaux",
		"editor.palette": "Objets",
		"editor.undo": "Annuler",
		"editor.redo": "Rétablir",
		"editor.playtest": "Tester",
		"editor.save": "Sauvegarder",
		"editor.export": "Exporter",
		"editor.import": "Importer",
		"editor.grid": "Grille",
		"editor.layers": "Calques",
		"editor.trigger": "Déclencheurs",
		"editor.search": "Rechercher",
		"editor.untitled": "Niveau sans titre",
		"editor.name": "Nom du niveau",
		"editor.music": "Musique",
		"editor.theme": "Thème",
		"editor.difficulty": "Difficulté",
		"editor.saved": "Niveau sauvegardé",
		"editor.exported": "Niveau copié dans le presse-papiers",
		"editor.imported": "Niveau importé",
		"editor.start_pos": "Position de départ",
		"editor.clear": "Vider",
		"editor.clear_confirm": "Vider tout le niveau ?",
		"daily": "Défi Quotidien",
		"daily.desc": "Un nouveau niveau chaque jour. Identique pour tous !",
		"daily.done": "Défi terminé ! Revenez demain.",
		"endless": "Mode Infini",
		"endless.desc": "Jusqu'où irez-vous ?",
		"endless.score": "Distance",
		"story": "Mode Histoire",
		"story.desc": "Suivez DEX sur le Circuit Néon",
		"boss": "Boss",
		"boss.warning": "LE WARDEN VOUS ATTEND",
		"level_locked": "Terminez les niveaux précédents",
		"leaderboard": "Classement",
		"leaderboard.local": "Records locaux",
		"leaderboard.global": "Global (bientôt)",
		"best_time": "Meilleur temps",
		"practice_best": "Record entraînement",
		"replay": "Replay",
		"ghost_beaten": "Vous avez battu votre fantôme !",
		"ghost_faster": "Le fantôme est devant",
		"new_record": "Nouveau record !",
		"achievement_unlocked": "Succès débloqué",
		"skip": "Passer",
		"next": "Suivant",
		"story_text.1": "Bienvenue sur le Circuit Néon.",
		"story_text.2": "Je suis DEX. C'est mon dash.",
		"story_text.3": "Chaque battement me porte.",
		"story_text.4": "Les portails courbent ma route. La gravité me trahit.",
		"story_text.5": "Les Wardens gardent les profondeurs.",
		"story_text.6": "Je les dépasserai tous.",
		"story_text.7": "Le Circuit ne se termine jamais...",
		"story_text.8": "...et moi non plus.",
		"fps": "FPS",
		"progress": "Progression",
		"restart_confirm": "Recommencer le niveau ?",
		"quit_confirm": "Quitter vers le menu ?",
		"delete_save": "Supprimer la sauvegarde",
		"delete_save_confirm": "Irréversible. Supprimer toute la progression ?",
		"reset": "Réinitialiser",
		"version": "Version",
		"controls_hint": "Espace / W / Haut - sauter | Échap - pause | R - recommencer",
		"how_to_play": "Maintenez pour sauter plus haut. Atterrissez pour tourner. Les portails changent tout.",
		"multilingual.credit": "Traductions contribuées par la communauté.",
	},
	"pt": {
		"app.title": "DEX DASH",
		"app.tagline": "um plataforma rítmico",
		"menu.play": "Jogar",
		"menu.story": "História",
		"menu.endless": "Infinito",
		"menu.daily": "Diário",
		"menu.editor": "Editor",
		"menu.custom": "Níveis Personalizados",
		"menu.settings": "Configurações",
		"menu.stats": "Estatísticas",
		"menu.achievements": "Conquistas",
		"menu.icons": "Ícones",
		"menu.quit": "Sair",
		"menu.continue": "Continuar",
		"menu.level_select": "Seleção de Nível",
		"menu.main_menu": "Menu Principal",
		"back": "Voltar",
		"yes": "Sim",
		"no": "Não",
		"ok": "OK",
		"cancel": "Cancelar",
		"confirm": "Confirmar",
		"retry": "Tentar de novo",
		"continue": "Continuar",
		"play": "Jogar",
		"practice": "Prática",
		"normal": "Normal",
		"easy": "Fácil",
		"hard": "Difícil",
		"harder": "Mais Difícil",
		"insane": "Insano",
		"extreme": "Extremo",
		"demon": "Demônio",
		"tutorial": "Tutorial",
		"level": "Nível",
		"coins": "Moedas",
		"attempts": "Tentativas",
		"jumps": "Pulos",
		"deaths": "Mortes",
		"time": "Tempo",
		"best": "Recorde",
		"complete": "Completo",
		"level_complete": "Nível Completo!",
		"level_failed": "Nível Falhou",
		"new_best": "Novo Recorde!",
		"coins_collected": "Moedas coletadas",
		"secret_found": "Segredo encontrado!",
		"press_enter": "Pressione Enter",
		"tap_anywhere": "Toque para começar",
		"loading": "Carregando",
		"paused": "Pausado",
		"resume": "Continuar",
		"restart": "Reiniciar",
		"quit_to_menu": "Voltar ao Menu",
		"checkpoint_reached": "Checkpoint!",
		"practice_mode": "Modo Prática",
		"auto_retry": "Tentativa automática",
		"ghost_mode": "Modo fantasma",
		"show_fps": "Mostrar FPS",
		"screen_shake": "Tremor de tela",
		"background_detail": "Detalhe do fundo",
		"particles": "Partículas",
		"quality": "Qualidade",
		"quality_low": "Baixa",
		"quality_medium": "Média",
		"quality_high": "Alta",
		"vsync": "VSync",
		"fps_limit": "Limite de FPS",
		"fullscreen": "Tela cheia",
		"resolution": "Resolução",
		"master_volume": "Volume geral",
		"music_volume": "Volume da música",
		"sfx_volume": "Volume dos efeitos",
		"language": "Idioma",
		"theme": "Tema de cores",
		"controls": "Controles",
		"rebind_jump": "Pular",
		"rebind_pause": "Pausa",
		"reset_controls": "Restaurar controles",
		"accessibility": "Acessibilidade",
		"reduced_motion": "Movimento reduzido",
		"high_contrast": "Alto contraste",
		"colorblind": "Modo daltônico",
		"ui_scale": "Escala da interface",
		"statistics": "Estatísticas",
		"stat.jumps": "Pulos totais",
		"stat.deaths": "Mortes totais",
		"stat.attempts": "Tentativas totais",
		"stat.time": "Tempo jogado",
		"stat.levels": "Níveis concluídos",
		"stat.coins": "Moedas coletadas",
		"stat.secret_coins": "Moedas secretas",
		"stat.endless": "Recorde infinito",
		"stat.daily": "Recorde diário",
		"stat.achievements": "Conquistas",
		"achievements": "Conquistas",
		"achievements_progress": "{0} de {1} desbloqueadas",
		"icon_shop": "Loja de Ícones",
		"icon_color": "Cor",
		"icon_trail": "Rastro",
		"buy": "Comprar",
		"equip": "Equipar",
		"owned": "Adquirido",
		"not_enough_coins": "Moedas insuficientes",
		"custom_levels": "Níveis Personalizados",
		"create_level": "Criar Nível",
		"play_custom": "Jogar",
		"edit": "Editar",
		"delete": "Excluir",
		"delete_confirm": "Excluir este nível?",
		"editor": "Editor de Níveis",
		"editor.palette": "Objetos",
		"editor.undo": "Desfazer",
		"editor.redo": "Refazer",
		"editor.playtest": "Testar",
		"editor.save": "Salvar",
		"editor.export": "Exportar",
		"editor.import": "Importar",
		"editor.grid": "Grade",
		"editor.layers": "Camadas",
		"editor.trigger": "Gatilhos",
		"editor.search": "Buscar",
		"editor.untitled": "Nível sem título",
		"editor.name": "Nome do nível",
		"editor.music": "Música",
		"editor.theme": "Tema",
		"editor.difficulty": "Dificuldade",
		"editor.saved": "Nível salvo",
		"editor.exported": "Nível copiado para a área de transferência",
		"editor.imported": "Nível importado",
		"editor.start_pos": "Posição inicial",
		"editor.clear": "Limpar",
		"editor.clear_confirm": "Limpar o nível inteiro?",
		"daily": "Desafio Diário",
		"daily.desc": "Um novo nível todo dia. Igual para todos!",
		"daily.done": "Diário concluído! Volte amanhã.",
		"endless": "Modo Infinito",
		"endless.desc": "Até onde você consegue ir?",
		"endless.score": "Distância",
		"story": "Modo História",
		"story.desc": "Siga DEX no Circuito Neon",
		"boss": "Chefe",
		"boss.warning": "O WARDEN O AGUARDA",
		"level_locked": "Conclua os níveis anteriores",
		"leaderboard": "Classificação",
		"leaderboard.local": "Recordes locais",
		"leaderboard.global": "Global (em breve)",
		"best_time": "Melhor tempo",
		"practice_best": "Recorde de prática",
		"replay": "Repetição",
		"ghost_beaten": "Você superou seu fantasma!",
		"ghost_faster": "O fantasma está à frente",
		"new_record": "Novo recorde!",
		"achievement_unlocked": "Conquista desbloqueada",
		"skip": "Pular",
		"next": "Próximo",
		"story_text.1": "Bem-vindo ao Circuito Neon.",
		"story_text.2": "Eu sou DEX. Este é meu dash.",
		"story_text.3": "Cada batida me leva adiante.",
		"story_text.4": "Portais curvam meu caminho. A gravidade me trai.",
		"story_text.5": "Os Wardens guardam as profundezas.",
		"story_text.6": "Vou superar todos eles.",
		"story_text.7": "O Circuito nunca termina...",
		"story_text.8": "...e eu também não.",
		"fps": "FPS",
		"progress": "Progresso",
		"restart_confirm": "Reiniciar o nível?",
		"quit_confirm": "Voltar ao menu?",
		"delete_save": "Apagar dados salvos",
		"delete_save_confirm": "Isso não pode ser desfeito. Apagar tudo?",
		"reset": "Redefinir",
		"version": "Versão",
		"controls_hint": "Espaço / W / Cima - pular | Esc - pausa | R - reiniciar",
		"how_to_play": "Segure para pular mais alto. Aterrisse para girar. Portais mudam tudo.",
		"multilingual.credit": "Traduções contribuídas pela comunidade.",
	},
	"ja": {
		"app.title": "DEX DASH",
		"app.tagline": "リズムプラットフォーマー",
		"menu.play": "プレイ",
		"menu.story": "ストーリー",
		"menu.endless": "エンドレス",
		"menu.daily": "デイリー",
		"menu.editor": "エディター",
		"menu.custom": "カスタムレベル",
		"menu.settings": "設定",
		"menu.stats": "統計",
		"menu.achievements": "実績",
		"menu.icons": "アイコン",
		"menu.quit": "終了",
		"menu.continue": "続きから",
		"menu.level_select": "レベル選択",
		"menu.main_menu": "メインメニュー",
		"back": "戻る",
		"yes": "はい",
		"no": "いいえ",
		"ok": "OK",
		"cancel": "キャンセル",
		"confirm": "確認",
		"retry": "リトライ",
		"continue": "続ける",
		"play": "プレイ",
		"practice": "練習",
		"normal": "ノーマル",
		"easy": "イージー",
		"hard": "ハード",
		"harder": "ハーダー",
		"insane": "インセイン",
		"extreme": "エクストリーム",
		"demon": "デーモン",
		"tutorial": "チュートリアル",
		"level": "レベル",
		"coins": "コイン",
		"attempts": "挑戦回数",
		"jumps": "ジャンプ",
		"deaths": "死亡",
		"time": "時間",
		"best": "ベスト",
		"complete": "達成",
		"level_complete": "レベルクリア！",
		"level_failed": "レベル失敗",
		"new_best": "新記録！",
		"coins_collected": "コイン獲得",
		"secret_found": "シークレット発見！",
		"press_enter": "Enterを押す",
		"tap_anywhere": "タップして開始",
		"loading": "読み込み中",
		"paused": "一時停止",
		"resume": "再開",
		"restart": "やり直す",
		"quit_to_menu": "メニューへ",
		"checkpoint_reached": "チェックポイント！",
		"practice_mode": "練習モード",
		"auto_retry": "自動リトライ",
		"ghost_mode": "ゴーストモード",
		"show_fps": "FPS表示",
		"screen_shake": "画面振動",
		"background_detail": "背景の詳細",
		"particles": "パーティクル",
		"quality": "品質",
		"quality_low": "低",
		"quality_medium": "中",
		"quality_high": "高",
		"vsync": "VSync",
		"fps_limit": "FPS上限",
		"fullscreen": "全画面",
		"resolution": "解像度",
		"master_volume": "マスターボリューム",
		"music_volume": "音楽",
		"sfx_volume": "効果音",
		"language": "言語",
		"theme": "カラーテーマ",
		"controls": "コントロール",
		"rebind_jump": "ジャンプ",
		"rebind_pause": "一時停止",
		"reset_controls": "コントロールをリセット",
		"accessibility": "アクセシビリティ",
		"reduced_motion": "動きを減らす",
		"high_contrast": "高コントラスト",
		"colorblind": "色覚モード",
		"ui_scale": "UIスケール",
		"statistics": "統計",
		"stat.jumps": "総ジャンプ回数",
		"stat.deaths": "総死亡回数",
		"stat.attempts": "総挑戦回数",
		"stat.time": "プレイ時間",
		"stat.levels": "クリア数",
		"stat.coins": "コイン獲得",
		"stat.secret_coins": "シークレットコイン",
		"stat.endless": "エンドレス記録",
		"stat.daily": "デイリー記録",
		"stat.achievements": "実績",
		"achievements": "実績",
		"achievements_progress": "{0}/{1} 解除済み",
		"icon_shop": "アイコンショップ",
		"icon_color": "カラー",
		"icon_trail": "トレイル",
		"buy": "購入",
		"equip": "装備",
		"owned": "所有",
		"not_enough_coins": "コインが足りません",
		"custom_levels": "カスタムレベル",
		"create_level": "レベル作成",
		"play_custom": "プレイ",
		"edit": "編集",
		"delete": "削除",
		"delete_confirm": "このレベルを削除しますか？",
		"editor": "レベルエディター",
		"editor.palette": "オブジェクト",
		"editor.undo": "元に戻す",
		"editor.redo": "やり直す",
		"editor.playtest": "テストプレイ",
		"editor.save": "保存",
		"editor.export": "エクスポート",
		"editor.import": "インポート",
		"editor.grid": "グリッド",
		"editor.layers": "レイヤー",
		"editor.trigger": "トリガー",
		"editor.search": "検索",
		"editor.untitled": "無題のレベル",
		"editor.name": "レベル名",
		"editor.music": "音楽",
		"editor.theme": "テーマ",
		"editor.difficulty": "難易度",
		"editor.saved": "保存しました",
		"editor.exported": "クリップボードにコピー",
		"editor.imported": "インポートしました",
		"editor.start_pos": "スタート位置",
		"editor.clear": "クリア",
		"editor.clear_confirm": "レベル全体を消去しますか？",
		"daily": "デイリーチャレンジ",
		"daily.desc": "毎日新しいレベル。みんな同じ！",
		"daily.done": "デイリー達成！また明日！",
		"endless": "エンドレスモード",
		"endless.desc": "どこまで行ける？",
		"endless.score": "距離",
		"story": "ストーリーモード",
		"story.desc": "ネオンサーキットでDEXを導け",
		"boss": "ボス",
		"boss.warning": "WARDENが待ち構えている",
		"level_locked": "前のレベルをクリアしよう",
		"leaderboard": "リーダーボード",
		"leaderboard.local": "ローカル記録",
		"leaderboard.global": "グローバル（近日公開）",
		"best_time": "ベストタイム",
		"practice_best": "練習ベスト",
		"replay": "リプレイ",
		"ghost_beaten": "ゴーストに勝った！",
		"ghost_faster": "ゴーストが先行中",
		"new_record": "新記録！",
		"achievement_unlocked": "実績解除",
		"skip": "スキップ",
		"next": "次へ",
		"story_text.1": "ネオンサーキットへようこそ。",
		"story_text.2": "私はDEX。これが私のダッシュ。",
		"story_text.3": "ビートが僕を前に運ぶ。",
		"story_text.4": "ポータルが道を曲げる。重力は裏切る。",
		"story_text.5": "WARDENが深層を守る。",
		"story_text.6": "全部追い抜いてやる。",
		"story_text.7": "サーキットは終わらない…",
		"story_text.8": "…僕も終わらない。",
		"fps": "FPS",
		"progress": "進捗",
		"restart_confirm": "レベルをやり直しますか？",
		"quit_confirm": "メニューに戻りますか？",
		"delete_save": "セーブデータを削除",
		"delete_save_confirm": "元に戻せません。全て削除しますか？",
		"reset": "リセット",
		"version": "バージョン",
		"controls_hint": "スペース / W / ↑ - ジャンプ | Esc - 一時停止 | R - リスタート",
		"how_to_play": "長押しで高くジャンプ。着地で回転。ポータルが全てを変える。",
		"multilingual.credit": "翻訳はコミュニティによるものです。",
	},
}
